# Generated by Django 5.0.6 on 2024-05-26 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('emoji', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/image/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('units', models.CharField(choices=[('Item', 'Item'), ('Weight', 'Weight')], default='Select unit', max_length=15)),
                ('stock', models.CharField(choices=[('Indefinite amount', 'Indefinite amount'), ('Fixed amount', 'Fixed amount'), ('Not available', 'Not available')], default='Select stock status', max_length=50)),
                ('selling_price', models.FloatField(default=0)),
                ('emoji', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/image/%Y/%m/%d/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.productsimages'),
        ),
    ]
