# Generated by Django 5.0.6 on 2024-05-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shops.basemodel')),
            ],
            bases=('shops.basemodel',),
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shops.basemodel')),
                ('image', models.ImageField(upload_to='products')),
            ],
            bases=('shops.basemodel',),
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shops.basemodel')),
                ('price', models.FloatField(db_default=0.0)),
                ('count', models.IntegerField(db_default=0)),
            ],
            bases=('shops.basemodel',),
        ),
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shops.basemodel')),
            ],
            bases=('shops.basemodel',),
        ),
    ]
